config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  devise_scope :user do
    resources :posts do
      resources :comments
    end
    get "users", to: "devise/sessions#new"
  end
devise_for :users,controllers: { sessions: "users/sessions", registrations: "users/registrations"}
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, :name, presence:true
    validates :description, length: { minimum: 10 }
    validates :user_id, presence:false
    belongs_to :user
    has_many :comments, dependent: :delete_all

  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: %i[show edit update destroy]
    before_action :authenticate_user!, except: [:index, :show]


    def index
        @posts = Post.all

    end



    def new
        @post = Post.new
    end

    def show
        @comment = Comment.new
        @comments = @post.comments
    end

    def edit
    end




    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id
        respond_to do |format|
            if @post.save
            format.html { redirect_to @post, notice: 'Post was successfully created.' }
            format.json { render :show, status: :created, location: @post }
            else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
            if @post.update(post_params)
            format.html { redirect_to @post, notice: 'Post was successfully Updated.' }
            format.json { render :show, status: :ok, location: @post }
            else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end




    def destroy
        # only the user who created the post can delete it
        if @post.user_id == current_user.id
            @post.destroy
        end

        respond_to do |format|
            format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

private

    def set_post
        @post = Post.find(params[:id])
    end


    def post_params
        params.require(:post).permit(:title, :description,:name, :published_at, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
    def date_time(post)
        post.created_at.strftime("%m/%d/%Y at %I:%M%p")
    end

  def username
    email.split('@')[0].capitalize
  end
end

app/views/posts/_form.html.erb
<div class="custom__container">
        <%= form_with(model: @post, local: true) do|f| %>

            <div class="wrapper">
                <%= f.label :title %>
                <%= f.text_field :title %>

                <%= f.label :description %>
                <%= f.text_area :description, rows: 1 %>

                <%= f.label :name %>
                <%= f.text_field :name %>   
            <%= f.submit %>
            <%= link_to "Back", posts_path, class: "back__link" %>

        <% end %>
   
</div>

app/views/posts/edit.html.erb
<h2 class="heading">Edit a post</h2>
<%=render "form", post: @post %>

app/views/posts/index.html.erb
<div class="container">
    <%@posts.each do|post|%>
        <div class="card">
            <h3><%= link_to post.title, post_path(post), class: "card__title" %></h3>
            <p class="card__content"><%=truncate(post.description, length:40, separator: ' ')%></p>

            <div class="card__date">
                <%=post.user.username %> 
            </div>
                <%= link_to "See More", post_path(post), class: "card__arrow" %>
        </div>
    <%end%>
</div>

app/views/posts/new.html.erb
<h2 class="heading">Add a post</h2>
<%=render "form", post: @post %>

app/views/posts/show.html.erb
<div class="show__container">
    <div class="wrapper">
        <h3 class="show__title"><%=@post.title%></h3>
            <p class="show__description"><%=@post.description%></p>

        <div class="configure">
            <%# if current user show the edit ang delete form %>
            <% if current_user == @post.user %>
                <%= link_to "Edit", edit_post_path(@post), class: "btn btn-primary" %>
                <%= button_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure to delete?" }, class: "btn btn-danger" %>
                </div>
            <% end %>

           <%# if only have a user account can comment this post  %>
            <% if current_user %>
                <div class="comment__container">
                    <h3 class="comment__title">Comments</h3>
                    <div class="comment__form">
                        <%= form_with model: @comment, url: post_comments_path(@post), local: true do |form| %>
                            <%= form.text_area :comment, class: "form-control", placeholder: "Write a comment" %>
                            <div class="comment-btn">
                            <%= form.submit "Comment", class: "btn btn-primary" %>
                            </div>
                        <% end %>
                    </div>
                    <div class="comment__list">
                        <% @post.comments.each do |comment| %>
                            <div class="comment__item">
                                <p class="comment__description"><%= comment.comment %></p>
                                </div>
                                 <% if current_user == @post.user || current_user == comment.user %>
                                    <%= button_to "Delete Comment", post_comment_path(@post, comment), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
                                <% end %>
                        <% end %>
                    </div>
                </div>
            <%# else only view the comments %>
            <% else %>
                <div class="comment__container">
                    <h3 class="comment__title">Comments</h3>
                    <div class="comment__list">
                        <% @post.comments.each do |comment| %>
                            <div class="comment__item">
                               
                                <p class="comment__description"><%= comment.comment %></p>
                               
                            </div>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>